package com.app.radiosatelital

data class RadioStation(
	val name: String,
	val country: String,
	val region: String,
	val url: String,
	val logoUrl: String? = null,
	val genre: String = "",
)

val defaultStations = listOf(
	RadioStation("La Mega", "Venezuela", "", "https://eu1.lhdserver.es:9007/stream"),
	RadioStation("Disney FM", "Perú", "", "https://27433.live.streamtheworld.com/DISNEY_PER_LM_SC"),
	RadioStation("Acqua", "Argentina", "Mar del Plata", "https://sonic-us.streaming-chile.com:7006/"),
	RadioStation("Acqua 100.1", "Argentina", "Villa Gesell", "https://strcdn.klm99.com:10983/acquapinamar"),
	RadioStation("Arceri", "Costa Rica", "Aserrín", "https://stream-178.zeno.fm/rmnr2cphyxhvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJybW5yMmNwaHl4aHZ2IiwiaG9zdCI6InN0cmVhbS0xNzguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImRYMW41R2s4U08yYWx2V0JKcHRDWEEiLCJpYXQiOjE3NjU0MTkxOTEsImV4cCI6MTc2NTQxOTI1MX0.KWxdZmmrrZmvw7-yDyEuMHt6eBzZ2z_OfEElTQVFrPQ"),
	RadioStation("Actitud", "México", "San Felipe", "https://radioenhd.com:8088/"),
	RadioStation("Actitud 100.9 FM", "Guatemala", "Ciudad de Guatemala", "https://ss.redradios.net:8002/stream"),
	RadioStation("Activa (Buenos Aires)", "Argentina", "Buenos Aires", "https://edge01.radiohdvivo.com/fmra1033"),
	RadioStation("Activa (Colombia)", "Colombia", "Tuquerres", "https://stream-177.zeno.fm/vkb12zqmgzzuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ2a2IxMnpxbWd6enV2IiwiaG9zdCI6InN0cmVhbS0xNzcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InVSNGNtcWRqUks2Q1dYb29xY2c5ckEiLCJpYXQiOjE3NjU0MTk2MDEsImV4cCI6MTc2NTQxOTY2MX0.mzmgEUJ2fr9JQ35IKW3sIeU7Ilioh400N-YjigAkiqM"),
	RadioStation("Activa (Salina Cruz)", "México", "Salina Cruz", "https://sp3.servidorrprivado.com/6617/"),
	RadioStation("Activa (Puerto Rico)", "Puerto Rico", "San Juan", "https://cast3.asurahosting.com/proxy/univers1/stream"),
	RadioStation("Activa 100.7", "Argentina", "News", "https://sh4.radioonlinehd.com:8533/stream"),
	RadioStation("Activa 12340 AM", "EE.UU", "Nashville", "https://ice66.securenetsystems.net/WNVL"),
	RadioStation("Activa 88.7", "Argentina", "Pocito", "https://streaming.radiosenlinea.com.ar/9088/stream"),
	RadioStation("Activa 92.5 CL", "Chile", "Chile", "https://stream-154.zeno.fm/pvs6hqz3crtvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJwdnM2aHF6M2NydHZ2IiwiaG9zdCI6InN0cmVhbS0xNTQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InpMR0Q1SEJRUWctazNNa3hNN2xVSXciLCJpYXQiOjE3NjU0MjA3NjcsImV4cCI6MTc2NTQyMDgyN30.R4EmPlaA0KfJ41x2S7efsqu98v_gkSg_7t9xV_Qcwvs"),
	RadioStation("Activa 95.1 FM Católica", "Guatemala", "Guatemala", "https://sh4.radioonlinehd.com:8557/stream"),
	RadioStation("Activa 99.7 FM", "Ecuador", "Santo Domingo de Los Colorado", "https://stream-142.zeno.fm/6n7fp9t2pceuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI2bjdmcDl0MnBjZXV2IiwiaG9zdCI6InN0cmVhbS0xNDIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ill2OUlFS2N0Um9pZFFaWDRvclJaQkEiLCJpYXQiOjE3NjU0MjA5NDMsImV4cCI6MTc2NTQyMTAwM30.ZOf-uJfL4P364hvHh9raQmkUFQKFLrMpakK8EeSkXPo"),
	RadioStation("Activa El Salvador", "El Salvador", "San Miguel", "https://stream-179.zeno.fm/ar1f9iuyvhgtv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhcjFmOWl1eXZoZ3R2IiwiaG9zdCI6InN0cmVhbS0xNzkuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InUzZHdHWGF4U3hpY01Rc3BQeWVvUmciLCJpYXQiOjE3NjU0MjEwMzgsImV4cCI6MTc2NTQyMTA5OH0.vcaNAVo91j9YcFO6MOW9XX2DMblnYGQ_yRXvm3yMhI0"),
	RadioStation("Activa FM (Chile)", "Chile", "Santiago Providencia", "https://27433.live.streamtheworld.com/ACTIVA.mp3"),
	RadioStation("Activa FM 93.5", "Argentina", "Los Cóndores", "https://streaming5.locucionar.com/proxy/activafm?mp=/stream"),
	RadioStation("Activa FM (Bolivia)", "Bolivia", "La Paz", "https://stream-179.zeno.fm/007z22fpx38uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIwMDd6MjJmcHgzOHV2IiwiaG9zdCI6InN0cmVhbS0xNzkuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IlBVYnFobWdOUlVHTU80M04zaDBXVWciLCJpYXQiOjE3NjU0MjE0MzUsImV4cCI6MTc2NTQyMTQ5NX0.j7G6_lvz-Dtb5lsSWIYiARLMAtIN5iy7WWKKjLuFnao"),
	RadioStation("Activa Jaén", "Perú", "Jaén, Cajamarca", "https://sp.onliveperu.com/8108/stream"),
	RadioStation("Activa La Paz", "Bolivia", "La Paz", "https://cloudstream2032.conectarhosting.com/9856/stream"),
	RadioStation("Activa Táchira Punta FM", "Venezuela", "San Cristóbal", "https://stream-157.zeno.fm/53vezhmmad0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI1M3ZlemhtbWFkMHV2IiwiaG9zdCI6InN0cmVhbS0xNTcuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ii1vUTExOGtSU1dlZG82cHVzZk1JOEEiLCJpYXQiOjE3NjU0MjE3MjEsImV4cCI6MTc2NTQyMTc4MX0.Xqb3C5FezGjrayWw84Zmpn9tkMV0AIz4gcy8X3V152M"),
	RadioStation("Radio Moda", "Perú", "Nacional", "https://25023.live.streamtheworld.com/CRP_MOD_SC"),
	RadioStation("Ritmo Romántica", "Perú", "Nacional", "https://25103.live.streamtheworld.com/CRP_RIT_SC"),
	RadioStation("Onda Cero", "Perú", "Nacional", "https://mdstrm.com/audio/6598b65ab398c90871aff8cc/icecast.audio"),
	RadioStation("La Zona", "Perú", "Nacional", "https://mdstrm.com/audio/5fada54116646e098d97e6a5/icecast.audio"),
	RadioStation("Radio Corazón", "Perú", "Nacional", "https://mdstrm.com/audio/5fada514fc16c006bd63370f/icecast.audio"),
	RadioStation("La Inolvidable", "Perú", "Nacional", "https://playerservices.streamtheworld.com/api/livestream-redirect/CRP_LI_SC"),
	RadioStation("Radio Mágica", "Perú", "Nacional", "https://26513.live.streamtheworld.com/MAG_AAC_SC"),
	RadioStation("Radiomar", "Perú", "Nacional", "https://24873.live.streamtheworld.com/CRP_MARAAC_SC"),
	RadioStation("RPP Noticias", "Perú", "Nacional", "https://mdstrm.com/audio/5fab3416b5f9ef165cfab6e9/icecast.audio"),
	RadioStation("Exitosa Noticias", "Perú", "Nacional", "https://neptuno-2-audio.mediaserver.digital/79525baf-b0f5-4013-a8bd-3c5c293c6561"),
	RadioStation("Radio PBO", "Perú", "Nacional", "https://stream.radiojar.com/2fse67zuv8hvv"),
	RadioStation("Radio Inca", "Perú", "Nacional", "https://stream.zeno.fm/b9x47pyk21zuv"),
	RadioStation("Radio ABN", "Perú", "Nacional", "https://jml-stream.com/radio/8000/radio.mp3"),
	RadioStation("Radio Abba Padre", "Perú", "Nacional", "https://stream-175.zeno.fm/6rrwumthg6quv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI2cnJ3dW10aGc2cXV2IiwiaG9zdCI6InN0cmVhbS0xNzUuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Im9XY2g3dmlTU0NHYlVGQ0QtZmNxUFEiLCJpYXQiOjE3NjQ3OTMwNDksImV4cCI6MTc2NDc5MzEwOX0.U3kdYbFm_XjuESzU_aSQ7owwkG9ScWV9h4fLn36I88U"),
	RadioStation("Radio Turbo Mix", "Perú", "Regional", "https://serverssl.innovatestream.pe:8080/167.114.118.120:7624/stream"),
	RadioStation("Radio Fuego", "Perú", "Regional", "https://serverssl.innovatestream.pe:8080/sp.onliveperu.com:8128/"),
	RadioStation("Radio Andina", "Perú", "Regional", "https://serverssl.innovatestream.pe:8080/http://167.114.118.120:7058/;stream"),
	RadioStation("Radio Ilucan", "Perú", "Regional", "https://serverssl.innovatestream.pe:8080/167.114.118.120:7820/;stream"),
	RadioStation("Radio Santa Lucía", "Perú", "Regional", "https://sp.dattavolt.com/8014/stream"),
	RadioStation("Radio Pampa Yurac", "Perú", "Regional", "https://rr5200.globalhost1.com/8242/stream"),
	RadioStation("Radio Stereo TV", "Perú", "Regional", "https://sp.onliveperu.com:7048/stream"),
	RadioStation("Radio La Kuadra", "Perú", "Regional", "https://dattavolt.com/8046/stream"),
	RadioStation("Radio Frecuencia", "Perú", "Regional", "https://conectperu.com/8384/stream"),
	RadioStation("Onda Popular (Lima)", "Perú", "Regional", "https://envivo.top:8443/am"),
	RadioStation("Onda Popular (Juliaca)", "Perú", "Regional", "https://dattavolt.com/8278/stream"),
	RadioStation("Radio Nor Andina", "Perú", "Regional", "https://mediastreamm.com/8012/stream/1/"),
	RadioStation("Radio Bambamarca", "Perú", "Regional", "https://envivo.top:8443/lider"),
	RadioStation("Radio Continente", "Perú", "Regional", "https://sonic6.my-servers.org/10170/"),
	RadioStation("La Cheverísima", "Perú", "Regional", "https://sp.onliveperu.com:8114/stream"),
	RadioStation("Radio TV El Shaddai", "Perú", "Regional", "https://stream.zeno.fm/ppr5q4q3x1zuv"),
	RadioStation("Radio Inica Digital", "Perú", "Regional", "https://stream.zeno.fm/487vgx80yuhvv"),
	RadioStation("Radio Activa", "Perú", "Regional", "https://sp.onliveperu.com:8108/stream"),
	RadioStation("Radio Mía", "Perú", "Regional", "https://streaming.zonalatinaeirl.com:8020/radio"),
	RadioStation("Radio Patrón", "Perú", "Regional", "https://streaming.zonalatinaeirl.com:8010/radio"),
	RadioStation("Radio TV Sureña", "Perú", "Regional", "https://stream.zeno.fm/p7d5fpx4xnhvv"),
	RadioStation("Radio Enamorados", "Perú", "Regional", "https://stream.zeno.fm/gnybbqc1fnruv"),
	RadioStation("Radio ABC (San Luis)", "México", "Norteamérica", "https://16643.live.streamtheworld.com/XHCZFM.mp3"),
	RadioStation("Radio ABC (Taxco)", "México", "Norteamérica", "https://streaming.servicioswebmx.com/8288/stream"),
	RadioStation("ABC 760", "México", "Norteamérica", "https://streamingcwsradio30.com/8292/stream"),
	RadioStation("ABC Radio Puebla", "México", "Norteamérica", "https://streaming.servicioswebmx.com/8264/stream"),
	RadioStation("Radio Acceso Total", "México", "Norteamérica", "https://us10a.serverse.com/proxy/acce8712?mp=/"),
	RadioStation("Ach Kuxlejal 100.3", "México", "Norteamérica", "https://stream-178.zeno.fm/md6tfkaaechvv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJtZDZ0ZmthYWVjaHZ2IiwiaG9zdCI6InN0cmVhbS0xNzguemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IkI4TUMzLXR3UTR1Q1VzbXY2M0gwUFEiLCJpYXQiOjE3NjQ3OTQ4MTksImV4cCI6MTc2NDc5NDg3OX0.xBJOxw_oGdW4sqNsL4n9WyUeK6CTvzAY8o5i5MjLe78"),
	RadioStation("ABC 94.7", "Argentina", "Sudamérica", "https://stream-176.zeno.fm/n03jc4xoy63tv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJuMDNqYzR4b3k2M3R2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Im9aa3kyRHRvUXBDU3kwNUF2OGdPX3ciLCJpYXQiOjE3NjQ3OTM2MzksImV4cCI6MTc2NDc5MzY5OX0.clgYVIm4DHZtHwGTjXdSfYi0SjVgGWj8UkiZEBz3yg0"),
	RadioStation("Estéreo Abejorral", "Colombia", "Sudamérica", "https://icecasthd.net/proxy/abejorral/live"),
	RadioStation("Abriendo Surcos", "Colombia", "Sudamérica", "https://djp.sytes.net/public/abriendo_surcos"),
	RadioStation("Acacio de Chile", "Chile", "Sudamérica", "https://sonic.portalfoxmix.cl:7057/"),
	RadioStation("Acción FM", "Venezuela", "Sudamérica", "https://stream-intervalohost.com:7008/stream"),
	RadioStation("Aclo Chuquisaca", "Bolivia", "Sudamérica", "https://cloudstream2030.conectarhosting.com/8192/stream"),
	RadioStation("Aclo Tarija", "Bolivia", "Sudamérica", "https://cloudstream2030.conectarhosting.com/8242/stream"),
	RadioStation("Radio La Hondureña", "Honduras", "Centroamérica", "https://s2.mkservers.space/rih"),
	RadioStation("Abriendo Los Cielos", "Honduras", "Centroamérica", "https://stream-177.zeno.fm/a8uwe88svy8uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhOHV3ZTg4c3Z5OHV2IiwiaG9zdCI6InN0cmVhbS0xNzcuemVuby4mbSIsInJ0dGwiOjUsImp0aSI6Ik9VWVRibTdpUVUtQjVhSHFOWUNyX1EiLCJpYXQiOjE3NjQ3OTQwOTQsImV4cCI6MTc2NDc5NDE1NH0.n3CeLd9U7rcF9A9NsPpzFGJJjuPsUoaf2EsUxGah04w"),
	RadioStation("Una Radio Viva Voz", "Nicaragua", "Centroamérica", "https://rr5100.globalhost1.com/8006/stream"),
	RadioStation("105.3 El Ritmo", "EE.UU", "Norteamérica", "https://n02b-e2.revma.ihrhls.com/zc3209/hls.m3u8?rj-ttl=5&rj-tok=AAABmuXcB-4Ad7qhABJqQGGBcg"),
	RadioStation("Acción Cristiana", "EE.UU", "Norteamérica", "https://panel.lifestreammedia.net:8162/stream"),
	RadioStation("RFI Internacional", "Francia", "Europa", "https://rfienespagnol64k.ice.infomaniak.ch/rfienespagnol-64.mp3"),
	RadioStation("RFI Español (96k)", "Francia", "Europa", "https://rfiespagnol96k.ice.infomaniak.ch/rfiespagnol-96k.mp3"),
	RadioStation("DW Español", "Alemania", "Europa", "https://dwstream6-lh.akamaihd.net/i/dwstream6_live@123544/master.m3u8"),
	RadioStation("RNE 5 (España)", "España", "Europa", "https://dispatcher.rndfnk.com/crtve/rne5/main/mp3/high?aggregator=tunein"),
	RadioStation("RNE Radio Clásica", "España", "Europa", "https://rnelivestream.rtve.es/rnerc/main/master.m3u8"),
	RadioStation("RNE Radio Nacional", "España", "Europa", "https://f141.rndfnk.com/star/crtve/rne1/nav/mp3/128/ct/stream.mp3?cid=01GENZSPVYG0R84NK9E1C77RSZ&sid=36LhA65FiO252hsvxBqzfqiI4HF&token=-FbGT-8Eif8zgFPSMX7ER3TPiwAZ4pI8BsNKr1HldC4&tvf=HsCHLkTgfRhmMTQxLnJuZGZuay5jb20"),
	RadioStation("Radio AFRONTAR", "España", "Europa", "https://vigo-copesedes-rrcast.flumotion.com/copesedes/vigo-low.mp3"),
	RadioStation("AB 95 FM", "España", "Europa", "https://stream-153.zeno.fm/szskq9dxs98uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJzenNrcTlkeHM5OHV2IiwiaG9zdCI6InN0cmVhbS0xNTMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ims0M0xwaVpDVE1pRXExWVhvMEpjUmciLCJpYXQiOjE3NjQ3OTI4NjUsImV4cCI6MTc2NDc5MjkyNX0.dpzu-0oLrJ2nsOJU25J8ghjMS2O_2FSyXzntk4rD05A"),
	RadioStation("Radio Tele Taxi", "España", "Europa", "https://radiott-web.streaming-pro.com:6103/radiott.mp3"),
	RadioStation("Radio ES", "España", "Europa", "https://libertaddigital-radio-live1.flumotion.com/libertaddigital/ld-live1-low.mp3"),
	RadioStation("Cadena COPE", "España", "Europa", "https://net1-cope-rrcast.flumotion.com/cope/net1-low.mp3"),
)